asf_doc_homepage:
    path: /doc
    defaults: { _controller: "ASFDocumentBundle:Backend:index" }
    
asf_doc_bundle_page:
    resource: "@ASFDocumentBundle/Resources/config/routing/Page.yml"
    prefix:   /doc/page
    
asf_doc_bundle_post:
    resource: "@ASFDocumentBundle/Resources/config/routing/Post.yml"
    prefix:   /doc/post