asf_document_page_list:
    path: /list
    defaults: { _controller: "ASFDocumentBundle:Page:list" }

asf_document_page_add:
    path: /add
    defaults: { _controller: "ASFDocumentBundle:Page:edit" }
        
asf_document_page_edit:
    path: /edit/{id}
    defaults: { _controller: "ASFDocumentBundle:Page:edit" }
        
asf_document_page_delete:
    path: /delete/{id}
    defaults: { _controller: "ASFDocumentBundle:Page:delete" }