asf_document_post_list:
    path: /list
    defaults: { _controller: "ASFDocumentBundle:Post:list" }
    
asf_document_post_add:
    path: /add
    defaults: { _controller: "ASFDocumentBundle:Post:edit" }
    
asf_document_post_edit:
    path: /edit/{id}
    defaults: { _controller: "ASFDocumentBundle:Post:edit" }
        
asf_document_post_delete:
    path: /delete/{id}
    defaults: { _controller: "ASFDocumentBundle:Post:delete" }